export type Language = "en" | "ar";

export const strings = {
  en: {
    appName: "EarnMaster",
    tagline: "Earn coins, redeem rewards",
    login: "Login",
    logout: "Logout",
    email: "Email",
    password: "Password",
    signIn: "Sign In",
    welcomeBack: "Welcome Back",
    loginSubtitle: "Sign in to start earning",
    dashboard: "Dashboard",
    tasks: "Tasks",
    wallet: "Wallet",
    profile: "Profile",
    totalCoins: "Total Coins",
    coinsEarned: "Coins Earned Today",
    tasksCompleted: "Tasks Completed",
    watchAd: "Watch Video Ad",
    watchAdDesc: "Watch a short video and earn 100 coins",
    earnCoins: "+100 Coins",
    watchingAd: "Watching Ad...",
    adComplete: "Ad Complete!",
    coinsAdded: "100 coins added to your wallet!",
    claim: "Claim Reward",
    balance: "Coin Balance",
    transactions: "Transaction History",
    noTransactions: "No transactions yet",
    earnedFromAd: "Watched Video Ad",
    coins: "Coins",
    availableTasks: "Available Tasks",
    dailyLimit: "Daily Limit",
    adsWatchedToday: "Ads watched today",
    of: "of",
    settings: "Settings",
    language: "Language",
    english: "English",
    arabic: "Arabic",
    version: "Version",
    coinValue: "Coin Value",
    coinValueDesc: "1000 coins = $1.00",
    skipAd: "Skip",
    adCountdown: "Ad ends in",
    seconds: "s",
    dailyBonus: "Daily Bonus",
    claimBonus: "Claim Daily Bonus",
    bonusClaimed: "Bonus already claimed today",
    greeting: "Hello",
    keepEarning: "Keep earning!",
    cashOut: "Cash Out",
    comingSoon: "Coming Soon",
    limitReached: "Daily limit reached",
    limitReachedDesc: "Come back tomorrow for more ads",
    invalidCredentials: "Invalid email or password",
    demoHint: "Use any email and password",
  },
  ar: {
    appName: "ماستر الأرباح",
    tagline: "اكسب عملات، احصل على مكافآت",
    login: "تسجيل الدخول",
    logout: "تسجيل الخروج",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    signIn: "دخول",
    welcomeBack: "مرحباً بعودتك",
    loginSubtitle: "سجّل دخولك وابدأ الكسب",
    dashboard: "الرئيسية",
    tasks: "المهام",
    wallet: "المحفظة",
    profile: "الملف",
    totalCoins: "إجمالي العملات",
    coinsEarned: "عملات اليوم",
    tasksCompleted: "المهام المنجزة",
    watchAd: "مشاهدة إعلان فيديو",
    watchAdDesc: "شاهد فيديو قصيراً واحصل على 100 عملة",
    earnCoins: "+١٠٠ عملة",
    watchingAd: "جارٍ مشاهدة الإعلان...",
    adComplete: "انتهى الإعلان!",
    coinsAdded: "تمت إضافة ١٠٠ عملة إلى محفظتك!",
    claim: "استلم المكافأة",
    balance: "رصيد العملات",
    transactions: "سجل المعاملات",
    noTransactions: "لا توجد معاملات بعد",
    earnedFromAd: "مشاهدة إعلان فيديو",
    coins: "عملات",
    availableTasks: "المهام المتاحة",
    dailyLimit: "الحد اليومي",
    adsWatchedToday: "الإعلانات المشاهدة اليوم",
    of: "من",
    settings: "الإعدادات",
    language: "اللغة",
    english: "الإنجليزية",
    arabic: "العربية",
    version: "الإصدار",
    coinValue: "قيمة العملة",
    coinValueDesc: "١٠٠٠ عملة = ١.٠٠ دولار",
    skipAd: "تخطي",
    adCountdown: "ينتهي الإعلان خلال",
    seconds: "ث",
    dailyBonus: "مكافأة يومية",
    claimBonus: "احصل على المكافأة اليومية",
    bonusClaimed: "تم استلام مكافأة اليوم",
    greeting: "مرحباً",
    keepEarning: "واصل الكسب!",
    cashOut: "سحب الأرباح",
    comingSoon: "قريباً",
    limitReached: "وصلت للحد اليومي",
    limitReachedDesc: "عد غداً لمزيد من الإعلانات",
    invalidCredentials: "البريد أو كلمة المرور غير صحيحة",
    demoHint: "استخدم أي بريد وكلمة مرور",
  },
};

export type StringKeys = keyof typeof strings.en;
